Repository doitintl/kube-no-trouble, pull requests merged in 2022-09, with the labels that each got.

#347 docs: Add example of scanning all files in a directory
  README.md
Labels: docs

#346 feat: Add support for detecting snapshot.storage.k8s.io/v1beta1
  fixtures/volumesnapshot-v1beta1.yaml
  fixtures/volumesnapshotclass-v1beta1.yaml
  fixtures/volumesnapshotcontent-v1beta1.yaml
  pkg/collector/cluster.go
  pkg/rules/rego/deprecated-future.rego
  test/rules_future_test.go
Labels: feature

#348 test: Reduce test noise level
  pkg/collector/collector_test.go
  pkg/judge/judge_test.go
  pkg/judge/rego_test.go
  test/helper.go
  test/helper_test.go
  test/rules_custom_test.go
Labels: test

#352 chore: Fixing spelling and add pre-commit for it
  .github/workflows/main.yaml
  .pre-commit-config.yaml
  README.md
  cmd/kubent/main_test.go
  pkg/collector/file_test.go
  pkg/collector/kube_test.go
  pkg/printer/filter_test.go
  scripts/install.sh
  test/helper_test.go
  test/rules_122_test.go
  test/rules_125_test.go
  test/rules_future_test.go
Labels: docs

#323 feat: Support for checking additional annotations
  README.md
  cmd/kubent/main.go
  fixtures/fake-deployment-v1beta1-with-kapp-annotation.yaml
  pkg/collector/cluster.go
  pkg/collector/cluster_test.go
  pkg/config/config.go
Labels: feature

#373 fix: Helm - only default to release namespace for namespaced resources
  pkg/collector/helm.go
  pkg/collector/helm2.go
  pkg/collector/helm3.go
  pkg/collector/helm_test.go
Labels: bug, fix

#371 ci: Notify users of the aarch64 option when installing
  scripts/install.sh
Labels: docs
